services:
  traefik:
    image: traefik:v2.10
    container_name: traefik_homework
    restart: unless-stopped
    ports:
      - "0.0.0.0:5034:80"
      - "0.0.0.0:100:443"
      - "0.0.0.0:8011:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro # Archivo de configuración principal
      - ./traefik/config:/etc/traefik/config:ro
    networks:
      - eam-elecitva-homework

  db_mysql_homework:
      build:
        context: ./MySQL
        dockerfile: Dockerfile
      container_name: mysql-homework
      volumes:
        - ./MySQL/mysql_data:/var/lib/mysql
      ports:
        - "3307:3306"
      networks:
        - eam-elecitva-homework
      healthcheck:
        test: [ "CMD","mysql", "-u", "grupo_vs", "-pgrupo_vs123*" ]
        interval: 30s
        timeout: 10s
        retries: 5
      labels:
        - "traefik.enable=false"

  adminer:
    image: adminer:latest
    container_name: adminer_homework
    restart: always
    # Add explicit port mapping for direct access
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql_homework
      - ADMINER_DESIGN=flat
    networks:
      - eam-elecitva-homework
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=PathPrefix(`/adminer`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.routers.adminer.entrypoints=web"

  api_homework:
    build:
      context: ./backend
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.75'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql:3306/mydatabase
    networks:
      - eam-elecitva-homework
    depends_on:
      - db_mysql_homework
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
        - "traefik.http.services.api.loadbalancer.server.port=8000"
        - "traefik.http.routers.api.entrypoints=web"
        - "traefik.http.services.api.loadbalancer.sticky=true"
        - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
        - "traefik.http.middlewares.api-strip.stripprefix.forceSlash=false"
        - "traefik.http.routers.api.middlewares=api-strip@docker"
        - "traefik.http.middlewares.api-headers.headers.customrequestheaders.X-Forwarded-Prefix=/api"

networks:
  eam-elecitva-homework:
    driver: bridge

volumes:
  mysql_data:
