FROM mysql:8.0

# Variables de entorno para MySQL
ENV MYSQL_ROOT_PASSWORD=root123*
ENV MYSQL_DATABASE=grupo_vs
ENV MYSQL_USER=grupo_vs
ENV MYSQL_PASSWORD=grupo_vs123*

# Exponer el puerto de MySQL
EXPOSE 3306